name: CICD

on:
# this "workflow_dispatch:" below state need to your action 
  workflow_dispatch:
    
jobs:
  
  code:
     runs-on: ubuntu-latest
     steps:
      - name: check out code
        run:  echo "code has come"
  build:
      runs-on: ubuntu-latest
     steps:
      - name: build the code
        run:  echo "code has build"
  test:
     runs-on: ubuntu-latest
     steps:
      - name: test the code
        run:  echo "code has test"
  deploye:
      runs-on: ubuntu-latest
     steps:
      - name: deploye the build
        run:  echo "deploye the "
