name: CICD

on:
  # This allows you to run the workflow manually
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
  build:
    runs-on: ubuntu-latest
    needs: code
    steps:
      - name: Build the code
        run: echo "Code has built"
    
      - name: Check the list of file
        run: ls ls

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test the code
        run: echo "Code has been tested"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy the build
        run: echo "Deploy the build"
