name: CICD

on:
  # This allows you to run the workflow manually
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        run: echo "Code has come"

  build:
    runs-on: ubuntu-latest
    needs: code
    steps:
      - name: Build the code
        run: echo "Code has built"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test the code
        run: echo "Code has been tested"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy the build
        run: echo "Deploy the build"
