name: hello

on:
  push:
    branches:
      - main
jobs:
  task:
    runs-on: ubuntu-latest

    steps:
      - name: this is first steps 
        run: echo "this is first steps"
        run python --version

      - name: this is the second steps
        run:  echo "this is the second steps"
